# Taps
tap "homebrew/bundle"

# Shell
brew "zsh"
brew "sheldon"

# Core CLI tools
brew "git"
brew "ghq"
brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "fd"

# File viewers
brew "eza"
brew "bat"

# Build tools
brew "mise"

# Git
brew "delta"
brew "difi"

# Editor
brew "neovim"
